import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
// import axios from 'axios';
// import loggerUtil from './api/logger/loggerutil';
// import configextentions from './api/config/configextensions';


// configextentions.loadConfig();
/* if (typeof window === "undefined") {
  //Add axios request logger
  axios.interceptors.request.use(loggerUtil.axiosRequestLogger);

  //Add axios response logger
  axios.interceptors.response.use(
    loggerUtil.axiosResponseLogger,
    loggerUtil.axiosErrorLogger
  );
} */

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [iagCode, setIagCode] = useState('');
  const [state, setState] = useState(''); 

  useEffect(() => {
    const queryParams = new URLSearchParams(window.location.search);
    setIagCode(queryParams.get('code'));
    setState(queryParams.get('state'))
  }, []);


  const logoutUrl = 'http://localhost:3000/api/logout?code='+encodeURIComponent(iagCode);
  const verifyUrl = 'http://localhost:3000/api/verify?code='+encodeURIComponent(iagCode)+'&state='+encodeURIComponent(state);
  const userUrl = 'http://localhost:3000/api/user?code='+encodeURIComponent(iagCode);
  const egiftUrl = 'http://localhost:3001/egift?code='+encodeURIComponent(iagCode)+'&state='+encodeURIComponent(state);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              target='_blank'
              rel='noopener noreferrer'
            >
              By{' '}
              <Image
                src='/vercel.svg'
                alt='Vercel Logo'
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src='/next.svg'
            alt='Next.js Logo'
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src='/thirteen.svg'
              alt='13'
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href='http://localhost:3000/api/login'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Login API <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Login features and&nbsp;API.
            </p>
          </a>

          <a
            href={verifyUrl}
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Verify <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href={userUrl}
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              User <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href={egiftUrl}
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              eGift <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
