import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

if (typeof window === "undefined") {
  const axios = require("axios");
  const loggerUtil = require("./api/logger/loggerutil");

  //Add axios request logger
  axios.interceptors.request.use(loggerUtil.axiosRequestLogger);

  //Add axios response logger
  axios.interceptors.response.use(
    loggerUtil.axiosResponseLogger,
    loggerUtil.axiosErrorLogger
  );
}

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [iagCode, setIagCode] = useState("");
  const [state, setState] = useState("");

  useEffect(() => {
    const queryParams = new URLSearchParams(window.location.search);
    setIagCode(queryParams.get("code") || "");
    setState(queryParams.get("state") || "");
  }, []);

  const logoutUrl = `/api/logout?code=${encodeURIComponent(iagCode)}`;
  const verifyUrl = `/api/verify?code=${encodeURIComponent(iagCode)}`;
  const userUrl = `/api/user?code=${encodeURIComponent(iagCode)}`;
  const egiftUrl = `/egift?code=${encodeURIComponent(iagCode)}`;

  const handleUrl = (url: string) => (e: React.MouseEvent<HTMLElement>) => {
    e.preventDefault();
    fetch(url)
      .then((res) => res.json())
      .then((data) => window.console.log("Title: " + data.title));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            {/* */}
            <Image
              src="https://content-prod-live.cert.starbucks.com/binary/v2/asset/137-82732.jpg"
              alt="13"
              width={40}
              height={20}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href={logoutUrl}
            onClick={() => handleUrl(logoutUrl)}
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Logout API <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Login features and&nbsp;API.
            </p>
          </a>

          <a
            href={verifyUrl}
            onClick={() => handleUrl(verifyUrl)}
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Verify <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href={userUrl}
            onClick={() => handleUrl(userUrl)}
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              User <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href={egiftUrl}
            onClick={() => handleUrl(egiftUrl)}
            className={styles.card}
            target="_self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              eGift <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
